ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev libjemalloc2 libvips libyaml-dev \
    pkg-config postgresql-client openssl ca-certificates && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Rails app lives here
WORKDIR /rails

# Set up development environment
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git

# Copy application code
COPY . .

# Add a script to be executed every time the container starts
COPY bin/docker-entrypoint /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint
ENTRYPOINT ["docker-entrypoint"]

# Expose port 3000
EXPOSE 3000

# Set SSL environment variables
ENV SSL_KEY_PATH=/rails/config/ssl/localhost.key \
    SSL_CERT_PATH=/rails/config/ssl/localhost.crt

# Start the main process with SSL
CMD ["bin/rails", "server", "-b", "0.0.0.0"]