name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_rate_limiter:
    name: Test Rate Limiter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rate_limiter
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.2'
        bundler-cache: true
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: bundle exec rspec

  test_job_marketplace:
    name: Test Job Marketplace API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./job_marketplace
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: job_marketplace_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.2'
        bundler-cache: true
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Setup test database
      run: |
        bin/rails db:create
        bin/rails db:schema:load
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/job_marketplace_test
        REDIS_URL: redis://localhost:6379/0
    - name: Generate SSL certificates for testing
      run: |
        mkdir -p config/ssl
        touch config/ssl/localhost.key
        touch config/ssl/localhost.crt
    - name: Run tests
      run: bundle exec rspec
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/job_marketplace_test
        REDIS_URL: redis://localhost:6379/0